name: Validate Changes
#test
on: [push]

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: |
          gh repo clone RedMan13/gam-cell-rules-parser
          node .
          gh repo commit RedMan13/gam-cell-rules-parser
