name: Validate Changes
#test
on: [push]


jobs:
  Validate:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Compile
        run: |
          gh repo clone RedMan13/gam-cell-rules-parser
          node ./gam-cell-rules-parser
          gh repo commit RedMan13/gam-cell-rules-parser
